all:
  children:
    ydb:
      hosts:
        static-node-1.ydb-cluster.com:
        static-node-2.ydb-cluster.com:
        static-node-3.ydb-cluster.com:

      vars:
        ansible_user: ubuntu
        ansible_ssh_common_args: "-o ProxyJump=ubuntu@static-node-1.ydb-cluster.com"
        ansible_ssh_private_key_file: "~/yandex"

        system_timezone: UTC
        system_ntp_servers: [time.cloudflare.com, time.google.com, ntp.ripe.net, pool.ntp.org]

        ydb_archive: "../ydbd-23.3.17-linux-amd64.tar.gz"
        ydb_config: "{{ ansible_config_file | dirname + '/files/config.yaml' }}"
        ydb_tls_dir: "../TLS/CA/certs/2024-05-03_07-25-00"

        ydb_user: root
        ydb_cores_static: 8 
        ydb_disks:
          - name: /dev/vdb
            label: ydb_disk_1
          - name: /dev/vdc
            label: ydb_disk_2
          - name: /dev/vdd
            label: ydb_disk_3
        ydb_allow_format_drives: true
        ydb_skip_data_loss_confirmation_prompt: false
        ydb_enforce_user_token_requirement: true
        # ydb_request_client_certificate - control dynamic nodes authentication in cluster
        # values: false - Do not require specific TLS certificate
        #         true  - Require specific TLS certificate to join the cluster
        # Default value: true (TODO change)
        ydb_request_client_certificate: true
        ydb_domain: Root
        ydb_dbname: database
        ydb_pool_kind: ssd
        ydb_database_groups: 8
        ydb_cores_dynamic: 8
        ydb_dynnodes:
          - { instance: 'a', offset: 0 }
          - { instance: 'b', offset: 1 }
        ydb_brokers:
          - static-node-1.ydb-cluster.com
          - static-node-2.ydb-cluster.com
          - static-node-3.ydb-cluster.com
        # ydbops_local - control cluster from localhost
        # values: false - use any static host for cluster control
        #         true  - use localhost for cluster control
        # Default value: true
        ydbops_local: true
        # ydbops_source_bin - binary for ydbops
        # values: ydbops - Linux x86_64
        #         ydbops_darwin_arm64 - MacOS Silicon M1/..
        #         ydbops_darwin_amd64 - MacOS Intel
        # Default value: ydbops
        ydbops_source_bin: ydbops