---

all:
  children:
    ydb:
      children:
        ydbd_static:
          hosts:
            ydb-node01.ru-central1.internal: 
            ydb-node02.ru-central1.internal:
            ydb-node03.ru-central1.internal:
        ydbd_dynamic:
          hosts:
            ydb-node01.ru-central1.internal: 
            ydb-node02.ru-central1.internal: 
            ydb-node03.ru-central1.internal: 
      vars:
        ansible_user: ansible
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no -A -J ansible@{{ lookup('env','JUMP_IP') }}"
        ansible_ssh_private_key_file: "~/.ssh/id_private_key"

        system_timezone: UTC
        system_ntp_servers: [time.cloudflare.com, time.google.com, ntp.ripe.net, pool.ntp.org]

        ydb_config: "{{ ansible_config_file | dirname + '/files/config.yaml' }}"
        ydb_tls_dir: "../../TLS/CA/certs/2024-10-03_15-04-35"
        ydb_version: "24.2.7"

        ydb_user: root
        ydb_cores_static: 6
        ydb_disks:
          - name: /dev/vdb
            label: ydb_disk_1
          - name: /dev/vdc
            label: ydb_disk_2
          - name: /dev/vdd
            label: ydb_disk_3
        ydb_allow_format_drives: true
        ydb_skip_data_loss_confirmation_prompt: yes
        ydb_enforce_user_token_requirement: true
        ydb_request_client_certificate: true
        ydb_domain: Root
        ydb_dbname: database
        ydb_pool_kind: ssd

        ydb_databases:
          database1:
            storage_units:
              - kind: ssd
                count: 1
          database2:
            storage_units:
              - kind: ssd
                count: 1

        ydb_database_groups: 4
        ydb_cores_dynamic: 9
        ydb_dynnodes:
          - { instance: 'a', offset: 0 }
          - { instance: 'b', offset: 1 }
        ydb_brokers:
          - ydb-node01.ru-central1.internal
          - ydb-node02.ru-central1.internal
          - ydb-node03.ru-central1.internal
        # ydbops_local - control cluster from localhost
        # values: false - use any static host for cluster control
        #         true  - use localhost for cluster control
        # Default value: false
        ydbops_local: false
        # ydbops_source_bin - binary for ydbops
        # values: ydbops - Linux x86_64
        #         ydbops_darwin_arm64 - MacOS Silicon M1/..
        #         ydbops_darwin_amd64 - MacOS Intel
        # Default value: ydbops
        ydbops_source_bin: ydbops
